### PR TITLE
Fix location and edge case of lab section issue

### LINKED ISSUE #194: Schedule parsing fails for lab section courses with hidden details
When importing schedules from Workday, certain lab section courses (e.g., `CHEM_V 121-L72`, `MATH_V 152-L2E`, `CHEM_V 123-L91`) fail to load in the extension calendar.

Reported by a user in Discord server:
Image

### PR DESCRIPTION
**Pull request by Vaten0x**
## Changes:

Corrected parsing logic for course location data.

Added handling for lab sections where details may not follow the standard format.

Fixes: [#194](https://github.com/mlool/workday-calendar-extension/issues/194)

Partially: [#195](https://github.com/mlool/workday-calendar-extension/issues/195) (instructor data still needs a proper fix)

### Screenshot after changes

image

Adding lab sections that were failing (CHEM_V 121-L72, MATH_V 152-L2E, CHEM_V 123-L91)

image

image

### CODE REVIEW

File: src/backends/workday/idSearchHelpers.ts [hunk 1]
```diff
@@ -84,26 +84,45 @@ export function parseSessionAndTerms(rawTerm: string[]): {
...
+      ;[
+        dateRange,
+        timeRange,
+        daysString,
+        roomNumber,
+        floorNumber,
+        buildingName,
+      ] = detailParts.reverse()
+
+      location = `${buildingName} - ${floorNumber} - ${roomNumber}`
```
Comment (ThatNerdSquared) [inline src/backends/workday/idSearchHelpers.ts:121]: previously the format was, e.g. `MATH-Floor 1-Room 102`. i think remove spaces + trim building name to building code (`Buchanan Building (BUCH)` -> `BUCH`)? we rely on this format to [properly generate the building link](https://github.com/mlool/workday-calendar-extension/blob/develop/src/content/SectionPopup/SectionInfoBody.tsx#L31), which you see in the popup
